[project]
name = "exercises"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "jax>=0.9.0",
    "numpy>=2.4.1",
    "pandas>=3.0.0",
    "polars>=1.38.1",
    "pyarrow>=23.0.0",
]

[tool.pyrefly]
project_includes = ["**/*.py"]
